### ISSUE TITLE
Create annotated tags for releases

### ISSUE THREAD

**Issue by benma** [facebookgo/httpdown#5]
Hi

It would be great if you tagged the current HEAD with v1.0.0, and in the future, occasionally bump the version and make new tags with new releases. I suggest using the semver.org versioning scheme, where you have major.minor.patch, and you bump the major for incompatible changes and the minor for compatible changes to the API.

**Comment by daaku** [comment]
I don't really mind tagging it with a version, but because we vendor and suggest vendoring to consumers of the library it's not something that will end up being done regularly and I'm afraid it will be a promise we'll fail to keep. At a high level though we take breaking changes to the API very seriously and would only really do it if we had to fix security issues or the like.
